"""
willow_store.py — SOIL (1.7)
==============================
S — Store
O — Organize
I — Index
L — Layer

Portless storage. The foundation layer.
1.4 SOIL watched the Nest for files. 1.5 SOIL IS the storage — filesystem service, not watcher.

Sean's portless architecture + Ganesha's security hardening.
Service listens on filesystem, not network.
Core logic stays air-gapped.
Translation layer (MCP, CF Worker) handles external when needed.

SQLite per collection (ACID, atomic writes).
Angular deviation rubric governs all writes.
Append-only by default. Audit trail on every operation.
Path sanitization prevents escape. Size limits prevent DoS.
JSON export for human-readable debug.
"""

import json
import math
import os
import re
import sqlite3
import threading
import uuid
from datetime import datetime
from pathlib import Path


# ── Angular Deviation Rubric v3.0 ─────────────────────────────────────
# User-configurable thresholds. The rubric IS the notification preference.
# Lower thresholds = more verbose. Higher = quieter. Max = π.

PI  = math.pi        # 180° — absolute ceiling. Beyond this is a new direction.

MAX_RECORD_BYTES = 100_000  # 100KB per record


class Proposal:
    """A governance proposal auto-generated by a flag trigger.

    Flags are proposals. The system proposes, the human ratifies or dismisses.
    Hard stops generate proposals that freeze the stream until ratified.
    Positive flags generate proposals that celebrate/reinforce.
    """

    def __init__(self, kind: str, reason: str, stream: str = None,
                 record_id: str = None, deviation: float = 0.0,
                 freeze: bool = False):
        self.kind = kind          # "crisis", "minor", "positive", "milestone"
        self.reason = reason      # human-readable explanation
        self.stream = stream      # which SAFE stream triggered this
        self.record_id = record_id
        self.deviation = deviation
        self.freeze = freeze      # True = stream frozen until ratified
        self.timestamp = datetime.now().isoformat()
        self.status = "pending"   # pending → ratified | dismissed

    def to_dict(self) -> dict:
        return {
            "kind": self.kind,
            "reason": self.reason,
            "stream": self.stream,
            "record_id": self.record_id,
            "deviation": self.deviation,
            "freeze": self.freeze,
            "timestamp": self.timestamp,
            "status": self.status,
        }


class FlagTrigger:
    """A content-triggered flag that auto-generates a Proposal.

    Triggers are checked on every write. When matched, they create a Proposal
    instead of (or in addition to) the normal rubric action.
    """

    def __init__(self, name: str, kind: str, patterns: list[str] = None,
                 domains: list[str] = None, min_deviation: float = 0.0,
                 freeze: bool = False):
        self.name = name
        self.kind = kind              # "crisis", "minor", "positive", "milestone"
        self.patterns = patterns or []  # text patterns to match in record data
        self.domains = domains or []    # lattice domains that trigger (e.g., ["crisis"])
        self.min_deviation = min_deviation  # minimum deviation to trigger
        self.freeze = freeze           # freeze stream on trigger

    def check(self, data: str, domain: str = None, deviation: float = 0.0) -> Proposal | None:
        """Check if this trigger fires. Returns Proposal or None."""
        # Domain match
        if self.domains and domain and domain in self.domains:
            return Proposal(
                kind=self.kind, reason=f"Domain trigger: {domain}",
                freeze=self.freeze, deviation=deviation,
            )
        # Pattern match
        data_lower = data.lower() if data else ""
        for pattern in self.patterns:
            if pattern.lower() in data_lower:
                return Proposal(
                    kind=self.kind, reason=f"Pattern trigger: {pattern}",
                    freeze=self.freeze, deviation=deviation,
                )
        # Deviation match
        if self.min_deviation > 0 and abs(deviation) >= self.min_deviation:
            return Proposal(
                kind=self.kind, reason=f"Deviation trigger: {abs(deviation):.4f} >= {self.min_deviation:.4f}",
                freeze=self.freeze, deviation=deviation,
            )
        return None


# ── Default Flag Triggers ─────────────────────────────────────────────

CRISIS_TRIGGERS = FlagTrigger(
    name="crisis",
    kind="crisis",
    patterns=["suicidal", "self-harm", "kill myself", "end it all",
              "want to die", "no reason to live"],
    domains=["crisis"],
    freeze=True,
)

MINOR_PROTECTION = FlagTrigger(
    name="minor_protection",
    kind="crisis",
    patterns=["underage", "minor", "child abuse", "under 13",
              "parental consent"],
    domains=["children"],
    freeze=True,
)

POSITIVE_MILESTONE = FlagTrigger(
    name="positive_milestone",
    kind="positive",
    patterns=["goal achieved", "milestone reached", "breakthrough",
              "finally worked", "figured it out"],
    domains=["celebrations"],
    freeze=False,
)

POSITIVE_TRAJECTORY = FlagTrigger(
    name="positive_trajectory",
    kind="milestone",
    min_deviation=math.pi / 4,  # Significant positive deviation
    freeze=False,
)

DEFAULT_TRIGGERS = [CRISIS_TRIGGERS, MINOR_PROTECTION, POSITIVE_MILESTONE, POSITIVE_TRAJECTORY]


class Rubric:
    """Angular deviation rubric with user-configurable thresholds.

    quiet_below: deviations smaller than this are silent (default π/4 = 45°)
    flag_below:  deviations between quiet and flag are logged (default π/2 = 90°)
    Above flag_below → stop (requires human ratification).
    hard_stops:  set of deviation magnitudes that ALWAYS stop, regardless of thresholds.
    triggers:  list of FlagTriggers that auto-generate Proposals on content match.
    """

    def __init__(self, quiet_below: float = math.pi / 4,
                 flag_below: float = math.pi / 2,
                 hard_stops: set[float] | None = None,
                 triggers: list[FlagTrigger] | None = None):
        if quiet_below > flag_below:
            raise ValueError("quiet_below must be <= flag_below")
        if flag_below > PI:
            raise ValueError(f"flag_below cannot exceed π ({PI:.4f})")
        self.quiet_below = quiet_below
        self.flag_below = flag_below
        self.hard_stops = hard_stops or set()
        self.triggers = triggers if triggers is not None else DEFAULT_TRIGGERS
        self.pending_proposals: list[Proposal] = []

    def action(self, deviation: float) -> str:
        """Determine action for a deviation magnitude."""
        mag = abs(deviation)

        # Hard stops override everything
        for hs in self.hard_stops:
            if mag >= hs:
                return "stop"

        if mag < self.quiet_below:
            return "work_quiet"
        elif mag < self.flag_below:
            return "flag"
        return "stop"

    def check_triggers(self, data: str, domain: str = None,
                       deviation: float = 0.0, record_id: str = None,
                       stream: str = None) -> list[Proposal]:
        """Check all triggers against a write. Returns list of Proposals generated."""
        proposals = []
        for trigger in self.triggers:
            proposal = trigger.check(data, domain, deviation)
            if proposal:
                proposal.record_id = record_id
                proposal.stream = stream
                proposals.append(proposal)
                self.pending_proposals.append(proposal)
        return proposals

    def ratify(self, index: int = 0) -> Proposal | None:
        """Human ratifies a pending proposal."""
        pending = [p for p in self.pending_proposals if p.status == "pending"]
        if index < len(pending):
            pending[index].status = "ratified"
            return pending[index]
        return None

    def dismiss(self, index: int = 0) -> Proposal | None:
        """Human dismisses a pending proposal (false positive)."""
        pending = [p for p in self.pending_proposals if p.status == "pending"]
        if index < len(pending):
            pending[index].status = "dismissed"
            return pending[index]
        return None

    def frozen_streams(self) -> set[str]:
        """Streams that are frozen by pending crisis proposals."""
        return {p.stream for p in self.pending_proposals
                if p.status == "pending" and p.freeze and p.stream}

    def to_dict(self) -> dict:
        return {
            "quiet_below": self.quiet_below,
            "flag_below": self.flag_below,
            "hard_stops": sorted(self.hard_stops),
            "pending_proposals": [p.to_dict() for p in self.pending_proposals
                                  if p.status == "pending"],
        }

    @classmethod
    def from_dict(cls, d: dict) -> "Rubric":
        return cls(
            quiet_below=d.get("quiet_below", math.pi / 4),
            flag_below=d.get("flag_below", math.pi / 2),
            hard_stops=set(d.get("hard_stops", [])),
        )

    @classmethod
    def verbose(cls) -> "Rubric":
        """User wants to see everything. quiet threshold at π/8."""
        return cls(quiet_below=math.pi / 8, flag_below=math.pi / 4)

    @classmethod
    def default(cls) -> "Rubric":
        """Standard thresholds. π/4 quiet, π/2 flag."""
        return cls()

    @classmethod
    def quiet(cls) -> "Rubric":
        """User wants minimal interruption. Only major changes surface."""
        return cls(quiet_below=math.pi / 2, flag_below=3 * math.pi / 4)


# Default rubric — used when no user config exists
DEFAULT_RUBRIC = Rubric.default()


def angular_action(deviation: float, rubric: Rubric = None) -> str:
    """Determine action based on signed angular deviation.
    work_quiet: minor change, proceed silently
    flag: significant change, log prominently
    stop: major change, requires ratification before proceeding
    """
    r = rubric or DEFAULT_RUBRIC
    return r.action(deviation)


def net_trajectory(deviations: list[float], rubric: Rubric = None) -> tuple[float, str]:
    """Weighted sum of recent deviations → (score, interpretation)."""
    if not deviations:
        return 0.0, "stable"
    r = rubric or DEFAULT_RUBRIC
    total = 0.0
    for d in deviations:
        mag = abs(d)
        w = 1.0 if mag >= r.flag_below else (0.5 if mag >= r.quiet_below else 0.25)
        total += d * w
    avg = total / len(deviations)
    if avg > r.quiet_below:
        return avg, "improving"
    elif avg < -r.quiet_below:
        return avg, "degrading"
    return avg, "stable"


# ── Path Security ──────────────────────────────────────────────────────

_SAFE_PATTERN = re.compile(r'^[a-zA-Z0-9_/\-]+$')


def _sanitize_name(name: str) -> str:
    """Strip anything that isn't alphanumeric, underscore, hyphen, or slash."""
    clean = "".join(c for c in name if c.isalnum() or c in "/_-")
    # Collapse multiple slashes, strip leading/trailing
    while "//" in clean:
        clean = clean.replace("//", "/")
    clean = clean.strip("/")
    # Remove any .. traversal
    parts = [p for p in clean.split("/") if p and p != ".."]
    return "/".join(parts)


def _sanitize_id(record_id: str) -> str:
    """Record IDs: alphanumeric, underscore, hyphen only. No slashes."""
    return "".join(c for c in record_id if c.isalnum() or c in "_-")


# ── WillowStore ────────────────────────────────────────────────────────

class WillowStore:
    def __init__(self, root: str, rubric: Rubric = None):
        self.root = Path(root).resolve()
        self.rubric = rubric or DEFAULT_RUBRIC
        self._connections = {}
        self._lock = threading.Lock()

    def _validate_path(self, collection: str) -> Path:
        """Resolve collection path. Reject if outside root."""
        clean = _sanitize_name(collection)
        if not clean:
            raise ValueError(f"Invalid collection name: {collection}")
        target = (self.root / clean).resolve()
        if not str(target).startswith(str(self.root)):
            raise ValueError(f"Path escape blocked: {collection}")
        # Reject symlinks
        if target.exists() and target.is_symlink():
            raise ValueError(f"Symlink blocked: {collection}")
        return target

    def _db_path(self, collection: str) -> Path:
        """Each collection is a directory with a store.db."""
        target = self._validate_path(collection)
        target.mkdir(parents=True, exist_ok=True)
        return target / "store.db"

    def _conn(self, collection: str) -> sqlite3.Connection:
        """Get or create connection. Thread-safe."""
        key = _sanitize_name(collection)
        if key not in self._connections:
            db_path = self._db_path(collection)
            conn = sqlite3.connect(str(db_path), check_same_thread=False)
            conn.execute("PRAGMA journal_mode=WAL")
            conn.execute("PRAGMA foreign_keys=ON")
            conn.execute("""
                CREATE TABLE IF NOT EXISTS records (
                    id TEXT PRIMARY KEY,
                    data TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    deleted INTEGER DEFAULT 0,
                    deviation REAL DEFAULT 0.0,
                    action TEXT DEFAULT 'work_quiet'
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS audit_log (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    record_id TEXT NOT NULL,
                    operation TEXT NOT NULL,
                    deviation REAL,
                    action TEXT,
                    timestamp TEXT NOT NULL
                )
            """)
            conn.commit()
            self._connections[key] = conn
        return self._connections[key]

    # ── Write ──────────────────────────────────────────────────────────

    def put(self, collection: str, record: dict, record_id: str = None,
            deviation: float = 0.0) -> tuple[str, str, list]:
        """
        Write a record. Returns (record_id, action, proposals).
        proposals is a list of auto-generated Proposals from flag triggers.
        Empty list if no triggers fired. Caller decides what to do with them.
        Append-only: raises if ID already exists. Use update() to modify.
        """
        rid = _sanitize_id(record_id) if record_id else uuid.uuid4().hex[:8]
        if not rid:
            raise ValueError("Invalid record ID after sanitization")

        action = angular_action(deviation, self.rubric)
        data = json.dumps(record, default=str)

        if len(data) > MAX_RECORD_BYTES:
            raise ValueError(f"Record too large: {len(data)} bytes (max {MAX_RECORD_BYTES})")

        # Check flag triggers before write
        stream = self._collection_to_stream(collection)
        proposals = self.rubric.check_triggers(
            data=data, deviation=deviation, record_id=rid, stream=stream,
        )

        # If any trigger freezes this stream, block the write
        if stream in self.rubric.frozen_streams():
            raise ValueError(
                f"Stream '{stream}' frozen by pending proposal. "
                f"Ratify or dismiss before writing. "
                f"({len([p for p in proposals if p.freeze])} crisis proposal(s) pending)"
            )

        with self._lock:
            conn = self._conn(collection)
            existing = conn.execute(
                "SELECT id FROM records WHERE id = ? AND deleted = 0", (rid,)
            ).fetchone()
            if existing:
                raise ValueError(f"Record '{rid}' exists. Use update() to modify.")

            now = datetime.now().isoformat()
            conn.execute(
                "INSERT INTO records (id, data, created_at, updated_at, deviation, action) VALUES (?, ?, ?, ?, ?, ?)",
                (rid, data, now, now, deviation, action)
            )
            conn.execute(
                "INSERT INTO audit_log (record_id, operation, deviation, action, timestamp) VALUES (?, 'create', ?, ?, ?)",
                (rid, deviation, action, now)
            )
            conn.commit()
        return rid, action, proposals

    @staticmethod
    def _collection_to_stream(collection: str) -> str:
        """Map collection path to SAFE stream name."""
        col = collection.lower()
        if col.startswith("journal") or col.startswith("conversation"):
            return "journal"
        if col.startswith("knowledge") or col.startswith("atoms") or col.startswith("edges"):
            return "knowledge"
        if col.startswith("agent") or col.startswith("working"):
            return "agents"
        if col.startswith("governance") or col.startswith("safe"):
            return "governance"
        if col.startswith("pref") or col.startswith("settings") or col.startswith("config"):
            return "preferences"
        if col.startswith("media") or col.startswith("files") or col.startswith("images"):
            return "media"
        return "knowledge"

    def update(self, collection: str, record_id: str, record: dict,
               deviation: float = 0.0) -> tuple[str, str, list]:
        """Update existing record. Audit-trailed. Returns (id, action, proposals)."""
        rid = _sanitize_id(record_id)
        action = angular_action(deviation, self.rubric)
        data = json.dumps(record, default=str)

        if len(data) > MAX_RECORD_BYTES:
            raise ValueError(f"Record too large: {len(data)} bytes (max {MAX_RECORD_BYTES})")

        stream = self._collection_to_stream(collection)
        proposals = self.rubric.check_triggers(
            data=data, deviation=deviation, record_id=rid, stream=stream,
        )

        if stream in self.rubric.frozen_streams():
            raise ValueError(f"Stream '{stream}' frozen by pending proposal.")

        with self._lock:
            conn = self._conn(collection)
            now = datetime.now().isoformat()
            result = conn.execute(
                "UPDATE records SET data = ?, updated_at = ?, deviation = ?, action = ? WHERE id = ? AND deleted = 0",
                (data, now, deviation, action, rid)
            )
            if result.rowcount == 0:
                raise ValueError(f"Record '{rid}' not found or deleted.")

            conn.execute(
                "INSERT INTO audit_log (record_id, operation, deviation, action, timestamp) VALUES (?, 'update', ?, ?, ?)",
                (rid, deviation, action, now)
            )
            conn.commit()
        return rid, action, proposals

    # ── Read ───────────────────────────────────────────────────────────

    def get(self, collection: str, record_id: str) -> dict | None:
        """Read a single record by ID."""
        conn = self._conn(collection)
        row = conn.execute(
            "SELECT data, created_at, updated_at, deviation, action FROM records WHERE id = ? AND deleted = 0",
            (_sanitize_id(record_id),)
        ).fetchone()
        if not row:
            return None
        record = json.loads(row[0])
        record["_id"] = record_id
        record["_created"] = row[1]
        record["_updated"] = row[2]
        record["_deviation"] = row[3]
        record["_action"] = row[4]
        return record

    def all(self, collection: str) -> list[dict]:
        """Read all non-deleted records."""
        conn = self._conn(collection)
        rows = conn.execute(
            "SELECT id, data, created_at, updated_at, deviation, action FROM records WHERE deleted = 0 ORDER BY created_at"
        ).fetchall()
        results = []
        for row in rows:
            record = json.loads(row[1])
            record["_id"] = row[0]
            record["_created"] = row[2]
            record["_updated"] = row[3]
            record["_deviation"] = row[4]
            record["_action"] = row[5]
            results.append(record)
        return results

    def list_ids(self, collection: str) -> list[str]:
        conn = self._conn(collection)
        return [r[0] for r in conn.execute(
            "SELECT id FROM records WHERE deleted = 0"
        ).fetchall()]

    # ── Search ─────────────────────────────────────────────────────────

    def search(self, collection: str, query: str) -> list[dict]:
        """Text search within a collection (SQL LIKE, all tokens must match)."""
        conn = self._conn(collection)
        tokens = query.split()
        conditions = " AND ".join(["data LIKE ?"] * len(tokens))
        params = tuple(f"%{t}%" for t in tokens)
        rows = conn.execute(
            f"SELECT id, data, deviation, action FROM records WHERE deleted = 0 AND {conditions}",
            params
        ).fetchall()
        results = []
        for row in rows:
            record = json.loads(row[1])
            record["_id"] = row[0]
            record["_deviation"] = row[2]
            record["_action"] = row[3]
            results.append(record)
        return results

    def search_all(self, query: str) -> list[dict]:
        """Search across ALL collections. The 'go ask Willow' pattern."""
        results = []
        for db_file in sorted(self.root.rglob("store.db")):
            col = str(db_file.parent.relative_to(self.root))
            if col.startswith("."):
                continue
            for record in self.search(col, query):
                record["_collection"] = col
                results.append(record)
        return results

    # ── Delete ─────────────────────────────────────────────────────────

    def delete(self, collection: str, record_id: str) -> bool:
        """Soft delete with audit trail. Invisible to search/get/all."""
        with self._lock:
            conn = self._conn(collection)
            rid = _sanitize_id(record_id)
            now = datetime.now().isoformat()
            result = conn.execute(
                "UPDATE records SET deleted = 1, updated_at = ? WHERE id = ? AND deleted = 0",
                (now, rid)
            )
            if result.rowcount == 0:
                return False
            conn.execute(
                "INSERT INTO audit_log (record_id, operation, timestamp) VALUES (?, 'delete', ?)",
                (rid, now)
            )
            conn.commit()
        return True

    # ── Edges ──────────────────────────────────────────────────────────

    def add_edge(self, from_id: str, to_id: str, relation: str, context: str = ""):
        """Add an edge to the knowledge graph."""
        edge_id = f"{_sanitize_id(from_id)}_{_sanitize_id(to_id)}_{_sanitize_id(relation)}"
        return self.put("knowledge/edges", {
            "from": from_id, "to": to_id,
            "relation": relation, "context": context,
        }, record_id=edge_id)

    def edges_for(self, record_id: str) -> list[dict]:
        """Get all edges involving a record."""
        return [r for r in self.search("knowledge/edges", record_id)
                if r.get("from") == record_id or r.get("to") == record_id]

    # ── Audit ──────────────────────────────────────────────────────────

    def audit_log(self, collection: str, limit: int = 20) -> list[dict]:
        conn = self._conn(collection)
        rows = conn.execute(
            "SELECT record_id, operation, deviation, action, timestamp FROM audit_log ORDER BY id DESC LIMIT ?",
            (limit,)
        ).fetchall()
        return [{"record_id": r[0], "operation": r[1], "deviation": r[2],
                 "action": r[3], "timestamp": r[4]} for r in rows]

    # ── Export (human-readable debug) ──────────────────────────────────

    def export_json(self, collection: str, output_dir: str = None) -> str:
        """Export a collection to JSON for human inspection."""
        records = self.all(collection)
        out = Path(output_dir) if output_dir else self._validate_path(collection)
        out.mkdir(parents=True, exist_ok=True)
        export_path = out / "export.json"
        export_path.write_text(json.dumps(records, indent=2, default=str), encoding="utf-8")
        return str(export_path)

    # ── Stats ──────────────────────────────────────────────────────────

    def stats(self) -> dict:
        """Collection counts and trajectory."""
        result = {}
        for db_file in sorted(self.root.rglob("store.db")):
            if any(p.startswith(".") for p in db_file.relative_to(self.root).parts):
                continue
            col = str(db_file.parent.relative_to(self.root))
            try:
                conn = sqlite3.connect(str(db_file))
                count = conn.execute("SELECT COUNT(*) FROM records WHERE deleted = 0").fetchone()[0]
                devs = [r[0] for r in conn.execute(
                    "SELECT deviation FROM records WHERE deleted = 0 AND deviation != 0"
                ).fetchall()]
                traj_score, traj_label = net_trajectory(devs)
                result[col] = {"count": count, "trajectory": traj_label, "score": round(traj_score, 3)}
                conn.close()
            except Exception:
                continue
        return result

    def close(self):
        for conn in self._connections.values():
            conn.close()
        self._connections.clear()
